AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - vendor/bundle/**/*
  RunRailsCops: true

inherit_from: .rubocop_todo.yml

AlignParameters:
  EnforcedStyle: with_fixed_indentation

ClassAndModuleChildren:
  EnforcedStyle: compact
