language: ruby
rvm:
  - 2.1.0
before_script:
  - psql -c 'create database refixative2_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake db:seed RAILS_ENV=test
script: bin/rake spec
branches:
  only:
    - next
