language: ruby
rvm:
  - 2.1.1
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database refixative;' -U postgres
  - bundle exec rake db:reset
script: 
  - bundle exec rake spec
branches:
  only:
    - next
