development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: refixative2_development
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: refixative2_production
  pool: 5
  timeout: 5000
