development:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: refixative2_development
  pool: 5
  timeout: 5000
  username: refixative2

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: refixative2_test
  pool: 5
  timeout: 5000
  username: refixative2

production:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: refixative2_production
  pool: 5
  timeout: 5000
  username: refixative2
